export const actionTypes = {
    SET_ADDRESSES: 'SET_ADDRESSES',
    ADD_ADDRESS: 'ADD_ADDRESS',
    UPDATE_ADDRESS: 'UPDATE_ADDRESS',
    DELETE_ADDRESS: 'DELETE_ADDRESS',
    SET_DEFAULT_ADDRESS: 'SET_DEFAULT_ADDRESS',
};
