export const actionTypes = {
    SET_PAYMENT_METHODS: 'SET_PAYMENT_METHODS',
    ADD_PAYMENT_METHOD: 'ADD_PAYMENT_METHOD',
    UPDATE_PAYMENT_METHOD: 'UPDATE_PAYMENT_METHOD',
    DELETE_PAYMENT_METHOD: 'DELETE_PAYMENT_METHOD',
    SET_LOADING: 'SET_LOADING',
};
