export const actionTypes = {
    SET_ACTIVE_GENDER: 'SET_ACTIVE_GENDER',
    SET_ACTIVE_CATEGORY: 'SET_ACTIVE_CATEGORY',
    SET_ACTIVE_SUBCATEGORY: 'SET_ACTIVE_SUBECATEGORY',
    SET_LOADING: 'SET_LOADING',
};
